/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package keylayout;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Dylan Taylor
 */
public class BoardPanel extends javax.swing.JPanel {

    final static int rowCount[] = {12, 12, 11, 10};
    final static int spacing = 10;
    final static int keySize = 60;
    final static int QWERTY_L = 100, COLEMAK_L = 200, DVORAK_L = 300;
    static int mode = QWERTY_L;
    static int total = 0;
    final static String lookup = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-=[];',./";
    final static String lookupALT = ")!@#$%^&*(abcdefghijklmnopqrstuvwxyz_+{}:\"<>?";
    final static String[] lookupTable = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "-", "=", "[", "]", ";", "'", ",", ".", "/"};
    static int[] frequency = new int[45];

    final char[][] colemak = {{'1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '='},
        {'Q', 'W', 'F', 'P', 'G', 'J', 'L', 'U', 'Y', ';', '[', ']'},
        {'A', 'R', 'S', 'T', 'D', 'H', 'N', 'E', 'I', 'O', '\''},
        {'Z', 'X', 'C', 'V', 'B', 'K', 'M', ',', '.', '/'}};
    final char[][] qwerty = {{'1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '='},
        {'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '[', ']'},
        {'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ';', '\''},
        {'Z', 'X', 'C', 'V', 'B', 'N', 'M', ',', '.', '/'}};
    final char[][] dvorak = {{'1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '[', ']'},
        {'\'', ',', '.', 'P', 'Y', 'F', 'G', 'C', 'R', 'L', '/', '='},
        {'A', 'O', 'E', 'U', 'I', 'D', 'H', 'T', 'N', 'S', '-'},
        {';', 'Q', 'J', 'K', 'X', 'B', 'M', 'W', 'V', 'Z'}};

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        for (int r = 0; r < 4; r++) {
            for (int k = 0; k < rowCount[r]; k++) {
                g.drawRect(30 + ((3 * spacing) * r) + k * (keySize + spacing), 30 + r * (spacing + keySize), keySize, keySize);
                g.setColor(new Color(255, 0, 0, (int) (255.0 * ((double) frequency[findChar(getCurrentKeyMap()[r][k])] / (double) total))));
                g.fillRect(30 + ((3 * spacing) * r) + k * (keySize + spacing), 30 + r * (spacing + keySize), keySize, keySize);
                g.setColor(Color.black);
                g.drawString("" + getCurrentKeyMap()[r][k], 55 + ((3 * spacing) * r) + k * (keySize + spacing), 55 + r * (spacing + keySize));
                g.drawString("" + frequency[findChar(getCurrentKeyMap()[r][k])], 55 + ((3 * spacing) * r) + k * (keySize + spacing), 75 + r * (spacing + keySize));
            }
        }
    }

    private int findChar(char c) {
        for (int i = 0; i < 45; i++) {
            if (c == lookup.charAt(i)) {
                return i;
            }
        }
        return -1;
    }

    private char[][] getCurrentKeyMap() {

        switch (mode) {
            case QWERTY_L:
                return qwerty;
            case COLEMAK_L:
                return colemak;
            case DVORAK_L:
                return dvorak;
            default:
                return qwerty;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
