/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package keylayout;

/**
 *
 * @author Dylan Taylor
 */
public class KeyboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form KeyboardFrame
     */
    public KeyboardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        qwertyButton = new javax.swing.JButton();
        colemakButton = new javax.swing.JButton();
        dvorakButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boardPanel = new keylayout.BoardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keyboard Layout Analysis Results");

        qwertyButton.setText("QWERTY");
        qwertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qwertyButtonActionPerformed(evt);
            }
        });
        jPanel2.add(qwertyButton);

        colemakButton.setText("Colemak");
        colemakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colemakButtonActionPerformed(evt);
            }
        });
        jPanel2.add(colemakButton);

        dvorakButton.setText("DVORAK");
        dvorakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvorakButtonActionPerformed(evt);
            }
        });
        jPanel2.add(dvorakButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jPanel1.add(boardPanel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qwertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qwertyButtonActionPerformed
        boardPanel.mode = BoardPanel.QWERTY_L;
        boardPanel.repaint();
    }//GEN-LAST:event_qwertyButtonActionPerformed

    private void colemakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colemakButtonActionPerformed
        boardPanel.mode = BoardPanel.COLEMAK_L;
        boardPanel.repaint();
    }//GEN-LAST:event_colemakButtonActionPerformed

    private void dvorakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvorakButtonActionPerformed
        boardPanel.mode = BoardPanel.DVORAK_L;
        boardPanel.repaint();
    }//GEN-LAST:event_dvorakButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyboardFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keylayout.BoardPanel boardPanel;
    private javax.swing.JButton colemakButton;
    private javax.swing.JButton dvorakButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton qwertyButton;
    // End of variables declaration//GEN-END:variables
}
